### ISSUE TITLE
some javascript for markdown and latex not working

### ISSUE THREAD

**Issue by walkerlala** [parpalak/upmath.me#1]
Hi, after successfully bring up `tex.s2cms.ru`, I realize that the `upmath.me` I have cloned still not working. Previously I think that problem may have something to do with `tex.s2cms.ru` not working. Now I have successfully bring up `tex.s2cms.ru`, but the `upmath.me` still cannot correctly colorize the page (texts on the left are not correctly highlighted, and nothing show up on the right).

What am I missing? Which javascript file is responsible for markdown/latex highlighting ?

Currently the logs are:

`php5-fpm` log:

    - -  18/Dec/2016:22:01:40 +0800 "GET /index.php" 200 /var/www/html/upmath.me/public_html/index.php 0.868 512 0.00%
    - -  18/Dec/2016:22:01:41 +0800 "GET /index.php" 200 /var/www/html/upmath.me/public_html/index.php 0.229 256 0.00%
    - -  18/Dec/2016:22:01:41 +0800 "GET /index.php" 200 /var/www/html/upmath.me/public_html/index.php 0.243 256 0.00%
    - -  18/Dec/2016:22:01:42 +0800 "GET /index.php" 200 /var/www/html/upmath.me/public_html/index.php 0.263 256 0.00%

upmath.me public_html `access.log`(nothing in `error.log`):

    127.0.0.1 - - [18/Dec/2016:22:01:40 +0800] "GET / HTTP/1.1" 200 3961 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:40 +0800] "GET /dist/css/style.min.css HTTP/1.1" 304 0 "http://oh.my.marktex.net/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:40 +0800] "GET /dist/js/vendors.min.js HTTP/1.1" 304 0 "http://oh.my.marktex.net/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:41 +0800] "GET /favicon.png HTTP/1.1" 200 296 "http://oh.my.marktex.net/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:41 +0800] "GET / HTTP/1.1" 200 3961 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:41 +0800] "GET /dist/css/style.min.css HTTP/1.1" 304 0 "http://oh.my.marktex.net/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:41 +0800] "GET /dist/js/vendors.min.js HTTP/1.1" 304 0 "http://oh.my.marktex.net/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:41 +0800] "GET /favicon.png HTTP/1.1" 200 296 "http://oh.my.marktex.net/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:41 +0800] "GET / HTTP/1.1" 200 3961 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:41 +0800] "GET /dist/css/style.min.css HTTP/1.1" 304 0 "http://oh.my.marktex.net/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:41 +0800] "GET /dist/js/vendors.min.js HTTP/1.1" 304 0 "http://oh.my.marktex.net/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:41 +0800] "GET /favicon.png HTTP/1.1" 200 296 "http://oh.my.marktex.net/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:42 +0800] "GET / HTTP/1.1" 200 3961 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:42 +0800] "GET /dist/css/style.min.css HTTP/1.1" 304 0 "http://oh.my.marktex.net/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:42 +0800] "GET /dist/js/vendors.min.js HTTP/1.1" 304 0 "http://oh.my.marktex.net/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"
    127.0.0.1 - - [18/Dec/2016:22:01:42 +0800] "GET /favicon.png HTTP/1.1" 200 296 "http://oh.my.marktex.net/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36"

nothing in `/var/log/php5-fpm.log`

nothing in `/var/log/nginx/access.log`

nothing in `/var/log/nginx/error.log`(just something like *nginx start...*)

I have setup `upmath.me` as I do for `tex.s2cms.ru`.

Any hint?

Thanks!

**Comment by parpalak** [comment]
Are there any errors in the browser console?

**Comment by walkerlala** [comment]
No, I cannot see any error in the browser console.

Which js files are responsible for highlighting the content? Maybe I can dive into it a little bit and find the cause.

**Comment by walkerlala** [comment]
I have find out the cause. Seems like that's because I have manually edit some js file, which cause cause it fail to be loaded.

**Comment by walkerlala** [comment]
Another issue.

How to adjust the link from `tex.s2cms.ru/svg/some-latex....` to `my.latex.host.net/svg/some-latex...` in the generated html so that I can get rid of dependency of `tex.s2cms.ru`? (my network connection to that host is really slow).

Thanks!

**Comment by parpalak** [comment]
You have to replace hosts in the source code. Searching through the repository will help you: https://github.com/parpalak/upmath.me/search?utf8=%E2%9C%93&q=tex.s2cms.ru

**Comment by walkerlala** [comment]
There are some weird errors when I change to source(as you stated):

    XMLHttpRequest cannot load http://my.latex.host.net/svg/in_t. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://oh.my.marktex.net' is therefore not allowed access.

Basically I just clone again from you repo, change the source and then install again. How to fix it?

**Comment by parpalak** [comment]
It's a standard CORS setting. I've added the following lines to [the image rendering location](https://github.com/parpalak/tex.s2cms.ru/blob/828d6ffda880c8060f33b923113924aa26db4334/nginx.conf.dist#L17):
```nginx
add_header 'Access-Control-Allow-Origin' '*' always;
add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;
```

**Comment by walkerlala** [comment]
Thanks, but I haven't see that yet. did you forget to commit or push?

By the way, in the default version of nginx I use on Ubuntu14.04, these two lines:

    add_header 'Access-Control-Allow-Origin' '*' always;
    add_header 'Access-Control-Allow-Methods' 'GET, OPTIONS' always;

always fail with(seem like the old version of nginx do not suport the word `always` in `add_header`). And manually compile/install nginx is messy. Do you have any idea to get around this?

**Comment by parpalak** [comment]
I've updated the nginx config sample.

I think you can safely remove the 'always' option: http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header
