### ISSUE TITLE
Can this be used fully client side?

### ISSUE THREAD

**Issue by atmoio** [parpalak/upmath.me#10]
This is a really beautiful editor. I checked out the demo and love the coloring + synchronized scroll. Is there a good way to strip this down so it works without a server? I'm willing to forgo the LaTeX support.

**Comment by parpalak** [comment]
Do you mean you want an editor without LaTeX support, Markdown only?

**Comment by atmoio** [comment]
Yes! I just really like the styling of your editor and overall UX. I haven't found anything like that before. Most don't pay attention to these details.

**Comment by zmyme** [comment]
This is almost the perfect editor to write some math article that I have ever find! But will it be possible to run fully locally? It would be much better if it could run without a server since sometimes Internet is not available. Thank you!

**Comment by parpalak** [comment]
Thanks for your questions. I'd like to recall that Upmath targets for preparing and publishing scientific texts for the web.

@mobitar This should be done in browsers by saving Upmath as HTML page. Right now there is something broken when such a page is opened again. I'll try to fix it.

@hydrogan Unfortunately, it's almost impossible. One may install TeX Live and wrapping web service locally (see https://github.com/parpalak/tex.s2cms.ru/issues/2). But it's too complicated.

**Comment by atmoio** [comment]
But it looks like even if you save the HTML page offline, the page still makes network requests to http://tex.s2cms.ru. Any way to disable that?

**Comment by parpalak** [comment]
I'll make a research. In my opinion it should work in the following way. If the text being edited contains formulas, the offline editor still should make requests to http://tex.s2cms.ru to obtain the pictures. If there is no formulas, it should not.

**Comment by zmyme** [comment]
@mobitar In fact  it seems okay to set up a local tex.s2cms.ru enviroment and change the link in the upmath to your local link, this should make it run fully locally but it is too complicated, and although there is a installation guide in this page https://github.com/parpalak/tex.s2cms.ru, it is still too hard for someone like me who do not have much experience on web development......

**Comment by parpalak** [comment]
@mobitar I've fixed the way how the offline page works. You can try it here: https://beta.upmath.me/
Just save the page in Chrome or Firefox and you can edit markdown without any internet connection.

**Comment by atmoio** [comment]
Love it, looks great!

**Comment by parpalak** [comment]
I've deployed it to https://upmath.me/.
