### ISSUE TITLE
Issues on iPad

### ISSUE THREAD

**Issue by junghoocho** [parpalak/upmath.me#11]
When I open the upmath.me editor in a browser on my iPad (iOS v11.3, both in Chrome or Safari), the markdown panel (the editor panel on the left) is rendered incorrectly. All text is “printed twice,” misaligned with each other. See the attached screen capture.

I opened the same editor on Mac and Android, and I don’t experience the same problem. So far it seems to be an iOS-specific issue.

![cdf031d5-1f1c-4fcc-a283-9760c5a113dc](https://user-images.githubusercontent.com/9000236/39736816-d18bc920-5236-11e8-9ae0-a9fd676d29a1.png)

**Comment by parpalak** [comment]
I've tried to figure out why this happens and haven't succeed. Unfortunately I have no iOS devices to debug the markup. Later I'll try again to do something.

**Comment by parpalak** [comment]
Well, I've found a report of a bug in iOS browsers: https://stackoverflow.com/questions/6890149/remove-3-pixels-in-ios-webkit-textarea
Could you please check if that workaround helps? You can try it here: https://beta.upmath.me/

**Comment by junghoocho** [comment]
![be212c21-3849-43d5-9b3a-606928580649](https://user-images.githubusercontent.com/9000236/39908333-87e84294-54a2-11e8-9cf4-0b0eb6d9016f.png)
Thank you! The beta site works fine on my iPad. It still does not work well on my iPhone, but I assume you added the workaround only for iPad? Thank you.

**Comment by junghoocho** [comment]
![bbc4ea40-cf23-461b-b2a5-7ef8405432d1](https://user-images.githubusercontent.com/9000236/39908377-b6b96526-54a2-11e8-9bec-707d3c242410.png) 

This is how it is now on iPad.

**Comment by junghoocho** [comment]
It seems that adding the following media query rules to editor.css makes the editor work on all my devices (Android Chrome, macOS Chrome and Safari, iPad and iPhone Safari and Chrome)

```css
@supports (-webkit-overflow-scrolling: touch) {
  /* CSS specific to iOS devices */
  textarea {
    margin-left: -3px !important;
  }
  textarea::placeholder {
    padding-left: 3px;
  }
}
```

The logic for checking "-webkit-overflow-scrolling" attribute is that only iOS mobile safari supports this attribute. (See https://stackoverflow.com/questions/30102792/css-media-query-target-only-ios-devices)

**Comment by parpalak** [comment]
That's weird. I've tried `margin-left: -3px !important;` and obtained the following result on BrowserStack: 

![](https://www.browserstack.com/screenshots/944f1e16f4daa4e309073d1d3c20a0f07ddacdbf/ios_iPad-Air_8.3_portrait.jpg)
As we see, an additional adjustment is required on the right.

My last fix is
```JS
if(/iPhone|iPad|iPod/i.test(navigator.userAgent)){
  textareas = document.getElementsByTagName('textarea');
  for(var i = 0; i < textareas.length; i++){
    textareas[i].style['padding-left'] = '13px'; // was 16px
    textareas[i].style['padding-right'] = '13px';  // was 16px
  }
}
```
It gives the right result:

![](https://www.browserstack.com/screenshots/11a176a62b2e69d6c79e9a5bcbdfbe92907e16ab/ios_iPad-Air_8.3_portrait.jpg)

I don't know why the rendered pictures are different. What iPhone do you have? What iOS version?

**Comment by junghoocho** [comment]
![img_0030](https://user-images.githubusercontent.com/9000236/39962110-420680e8-55fa-11e8-9c43-cb4df72d97c9.PNG)

This is how the page https://beta.upmath.me looks on my iPhone now. It looks almost perfect but slightly off. On my iPad, it works perfectly. I am OK with as it looks on my iPhone, since it is mostly a cosmetic issue and I primarily use iPad. I have an iPhone 6 with iOS 11.3

**Comment by atmoio** [comment]
In addition to the [3px issue](https://stackoverflow.com/questions/6890149/remove-3-pixels-in-ios-webkit-textarea), I found that on mobile Safari, the underlay text is rendered with different line breaks. For example, with the sample text `Create web articles and blog posts with equations and diagrams`, the textarea would render `posts with equations` on one line, while the underlay would render `posts` on one line and `with equations` on another line. 

The solution was adding:

``` css
pre.ldt-pre {
  -webkit-nbsp-mode: space;
}
```

combined with:

``` css
@supports (-webkit-overflow-scrolling: touch) {
  .ldt pre {
    margin-left: 3px !important;
  }
}
```

That seemed to have fixed the issue completely.

**Comment by parpalak** [comment]
Thanks for reporting, I'll try to apply the `-webkit-nbsp-mode` rule.

**Comment by parpalak** [comment]
Sorry for delay, but I cannot reproduce the issue:

![ipad screenshot](https://s3.amazonaws.com/media.crossbrowsertesting.com/users/604344/screenshots/window/zfde556cdd4eaa19221a.png)

**Comment by atmoio** [comment]
I just launched the iPhone X simulator running iOS 12.1 and got this:

![simulator screen shot - iphone x - 2019-02-03 at 10 11 05](https://user-images.githubusercontent.com/3277844/52179133-127bde80-279c-11e9-90c2-c4115abe3b70.png)

This is related to  `-webkit-nbsp-mode`.

**Comment by parpalak** [comment]
Well, I've tested the site on a real device. As you can see, it works fine in both Safari and Chrome:

![2019-03-07 19 43 16](https://user-images.githubusercontent.com/9402484/54035240-f23fa500-41c9-11e9-9e63-6348cf81efe5.jpg)
![2019-03-07 19 43 45](https://user-images.githubusercontent.com/9402484/54035275-08e5fc00-41ca-11e9-80ce-2399128e3f29.jpg)
