### ISSUE TITLE
run parserCollection.updateResult() when automatic (not user direct input) input happens in the textarea

### ISSUE THREAD

**Issue by sajozsattila** [parpalak/upmath.me#18]
The issue is happening with Firefox and Grammarly with me, but I guess it is same with different spellcheck.  
The Grammary change the text area content, however, it does not fire parserCollection.updateResult();

See example bellow:
![error](http://mur2.co.uk/_uploads/photos/attila/upmath_error_1.png)

**Comment by parpalak** [comment]
Seems like this extension directly modifies the `value` attribute of the textarea without triggering any events. I'll try to find the workaround. Related question: https://stackoverflow.com/questions/36953235/detect-textarea-value-change-programmatically
