### ISSUE TITLE
latex not properly centralized in the generated html

### ISSUE THREAD

**Issue by walkerlala** [parpalak/upmath.me#2]
Hi,
I have been using upmath.me for a while, and discover that the latex svg would not be centralized if I copy the generated html and paste it in some other html. Not even a very simple html.

The problem is in this [line](https://github.com/parpalak/upmath.me/blob/48c639034e998bc93b92382aac0916d55686c1e0/public_html/src/js/markdown-it-s2-tex.js#L170)

    <img align="center" src= ...

It turn out this javascript will generate something like:

    <p><img align="cener" src=...></p>

for non-inline latex img. But the generated latex img won't be aligned to center.

I don't have much experience in HTML, but with a quick search on google I discover that changing the generated html to this would work:

    <p><div style="display: flex; justify-content: center;"><img src=...    ></div></p>

Will this be OK to change the rule in [mark-down-it-s2-tex.js](https://github.com/parpalak/upmath.me/blob/48c639034e998bc93b92382aac0916d55686c1e0/public_html/src/js/markdown-it-s2-tex.js) ?

**Comment by parpalak** [comment]
Thanks for reporting. I've fixed it in another way.
