### ISSUE TITLE
Text appears twice (overlayed) while editing

### ISSUE THREAD

**Issue by wmustafaAwad** [parpalak/upmath.me#22]
Hi there, parpalak. Thanks for the amazing tool.

I have been using the tool when all of a sudden (While editing text) the following happened:
![image](https://user-images.githubusercontent.com/40274507/87857446-f97ed300-c926-11ea-92fb-569137886bd4.png)

The text I am writing got duplicated and overlayed. The only accessible text is the grey text (i.e. I can select and edit it). However, any edit I make appears and the blue and green-highlighted text. 
I am not sure why this happens. I am using google chrome.

**Comment by parpalak** [comment]
Hello,

I suppose it can be caused by one of extensions installed. Can you check if it is happening in a private window of Google Chrome?

**Comment by wmustafaAwad** [comment]
Hi @parpalak 

I assume so.
I tried to replicate the error in a chrome incognito window and it did not occur.
Thanks for your help. 
Will add a comment if I figured out which extension did it, but for now, I will close the issue.
