### ISSUE TITLE
add functionalities to support multiple documents

### ISSUE THREAD

**Issue by weidezhang** [parpalak/upmath.me#24]
feature request

**Comment by parpalak** [comment]
This feature is in the distant plans. Now you can save and open files from your computer.

**Comment by weidezhang** [comment]
got it. thanks.

**Comment by parpalak** [comment]
As they say, better late than never. I figured out how to make working with multiple documents in the browser possible. You can try it out in the new version. Additional information is available in the release notes: https://upmath.me/whatsnew.html
