### ISSUE TITLE
proper indentation of very long latex formulae

### ISSUE THREAD

**Issue by walkerlala** [parpalak/upmath.me#3]
I have tried many measures, but I still can't properly indent a very long latex formulae so that it looks better:

![image](https://cloud.githubusercontent.com/assets/11005974/21578069/bdbd821a-cfad-11e6-81d4-9d5df1721793.png)

This is a img I cut from one of my blog. As you can see, the formulae is too long to fix in the frame.

I try to put two `\linebreak` before the `=` mark. But now it look like this:

![image](https://cloud.githubusercontent.com/assets/11005974/21578083/0d5ccc36-cfae-11e6-9771-842eee8a4557.png)

which still tastes not so good.

Ideally, I would like it to be something like this:

![image](https://cloud.githubusercontent.com/assets/11005974/21578087/56312e84-cfae-11e6-8639-e119146843f7.png)

Is this possible on `upmath.me` ?

Thanks!

**Comment by parpalak** [comment]
This question is not related to my editor. It's about LaTeX.

In such cases I split equations "by hands". Here is an example:

[![formula sample](https://tex.s2cms.ru/svg/%5Cbegin%7Balign*%7D%0A%5Cvec%7BP%7D_%5Ctext%7B%D1%81%D0%BA%D1%80%7D%26%3D-%7B1%5Cover%204%5Cpi%20c%7D%5Cint%5Cvarphi%5C%2C%5Cnabla%5Ctimes%5Cvec%7BB%7D%5C%2CdV%3D-%7B1%5Cover%204%5Cpi%20c%7D%5Cint%5Cleft(%5Cnabla%5Ctimes%5Cvarphi%5Cvec%7BB%7D-%5Cnabla%5Cvarphi%5Ctimes%5Cvec%7BB%7D%5Cright)%5C%2CdV%3D%5C%5C%0A%26%3D%7B1%5Cover%204%5Cpi%20c%7D%5Coint%5Cvarphi%5Cvec%7BB%7D%5Ctimes%20d%5Cvec%7BS%7D-%7B1%5Cover%204%5Cpi%20c%7D%5Cint%5Cvec%7BE%7D%5Ctimes%5Cvec%7BB%7D%5C%2CdV%3D-%7B1%5Cover%20c%5E2%7D%5Cint%5Cvec%7BS%7D%5C%2CdV%3D-%5Cvec%7BP%7D_%5Ctext%7B%D1%8D%D0%BC%7D.%0A%5Cend%7Balign*%7D)](https://tex.s2cms.ru/g/%5Cbegin%7Balign*%7D%0A%5Cvec%7BP%7D_%5Ctext%7B%D1%81%D0%BA%D1%80%7D%26%3D-%7B1%5Cover%204%5Cpi%20c%7D%5Cint%5Cvarphi%5C%2C%5Cnabla%5Ctimes%5Cvec%7BB%7D%5C%2CdV%3D-%7B1%5Cover%204%5Cpi%20c%7D%5Cint%5Cleft(%5Cnabla%5Ctimes%5Cvarphi%5Cvec%7BB%7D-%5Cnabla%5Cvarphi%5Ctimes%5Cvec%7BB%7D%5Cright)%5C%2CdV%3D%5C%5C%0A%26%3D%7B1%5Cover%204%5Cpi%20c%7D%5Coint%5Cvarphi%5Cvec%7BB%7D%5Ctimes%20d%5Cvec%7BS%7D-%7B1%5Cover%204%5Cpi%20c%7D%5Cint%5Cvec%7BE%7D%5Ctimes%5Cvec%7BB%7D%5C%2CdV%3D-%7B1%5Cover%20c%5E2%7D%5Cint%5Cvec%7BS%7D%5C%2CdV%3D-%5Cvec%7BP%7D_%5Ctext%7B%D1%8D%D0%BC%7D.%0A%5Cend%7Balign*%7D)

**Comment by walkerlala** [comment]
Thanks, but adding `\begin{align*}` and `\end{align*}` doesn't seem to work sometimes. For example, how do you align this?

```
https://tex.s2cms.ru/g/%7B%5Cpartial%20E%20%5Cover%20%5Cpartial%20y_o%7D%0A%20%26%3D%20%7B%7B%5Cpartial%20%7B%7B1%20%5Cover%202%7D%20%5Cdisplaystyle%5Csum_%7Bk%3D1%7D%5Eq%20(y_%7Bd%2Ck%7D-y_k)%5E2%7D%20%5Cover%20%5Cpartial%20y_o%7D%0A%20%26%3D%20%7B1%20%5Cover%202%7D%20%5Cdisplaystyle%5Csum_%7Bk%3D1%7D%5Eq%20%7B%5Cpartial%20(y_%7Bd%2Ck%7D-y_k)%5E2%20%5Cover%20%5Cpartial%20y_o%7D%0A%20%26%3D%20%7B1%20%5Cover%202%7D%20%5Cdisplaystyle%5Csum_%7Bk%3D1%7D%5Eq%20%7B%7B%5Cpartial%20(y_%7Bd%2Ck%7D-y_k)%5E2%20%5Cover%20%5Cpartial%20y_k%7D%5Ccdot%7B%5Cpartial%20y_k%20%5Cover%20%5Cpartial%20y_o%7D%7D%5C%5C%0A%20%26%3D%20-%20%5Cdisplaystyle%5Csum_%7Bk%3D1%7D%5Eq%20(y_%7Bd%2Ck%7D-y_k)%20%5Ccdot%20%7B%5Cpartial%20y_k%20%5Cover%20%5Cpartial%20y_o%7D%0A%20%26%3D%20-%20%5Cdisplaystyle%5Csum_%7Bk%3D1%7D%5Eq%20e_k%20%5Ccdot%20%7B%5Cpartial%20y_k%20%5Cover%20%5Cpartial%20y_o%7D
```

I try to add  `\begin{align*}` and `\end{align*}` , but that doesn't seem to work.

Thanks for you help again.

**Comment by parpalak** [comment]
There is a syntax error: an extra opening bracket '{'. I've fixed it:

[![formula](https://tex.s2cms.ru/svg/%5Cbegin%7Balign*%7D%7B%5Cpartial%20E%20%5Cover%20%5Cpartial%20y_o%7D%0A%20%26%3D%20%7B%5Cpartial%20%7B%7B1%20%5Cover%202%7D%20%5Csum%5Climits_%7Bk%3D1%7D%5Eq%20(y_%7Bd%2Ck%7D-y_k)%5E2%7D%20%5Cover%20%5Cpartial%20y_o%7D%0A%20%3D%20%7B1%20%5Cover%202%7D%20%5Csum_%7Bk%3D1%7D%5Eq%20%7B%5Cpartial%20(y_%7Bd%2Ck%7D-y_k)%5E2%20%5Cover%20%5Cpartial%20y_o%7D%0A%20%3D%20%7B1%20%5Cover%202%7D%20%5Csum_%7Bk%3D1%7D%5Eq%20%7B%7B%5Cpartial%20(y_%7Bd%2Ck%7D-y_k)%5E2%20%5Cover%20%5Cpartial%20y_k%7D%5Ccdot%7B%5Cpartial%20y_k%20%5Cover%20%5Cpartial%20y_o%7D%7D%5C%5C%0A%20%26%3D%20-%20%5Csum_%7Bk%3D1%7D%5Eq%20(y_%7Bd%2Ck%7D-y_k)%20%5Ccdot%20%7B%5Cpartial%20y_k%20%5Cover%20%5Cpartial%20y_o%7D%0A%20%3D%20-%20%5Csum_%7Bk%3D1%7D%5Eq%20e_k%20%5Ccdot%20%7B%5Cpartial%20y_k%20%5Cover%20%5Cpartial%20y_o%7D%0A%5Cend%7Balign*%7D)](https://tex.s2cms.ru/g/%5Cbegin%7Balign*%7D%7B%5Cpartial%20E%20%5Cover%20%5Cpartial%20y_o%7D%0A%20%26%3D%20%7B%5Cpartial%20%7B%7B1%20%5Cover%202%7D%20%5Csum%5Climits_%7Bk%3D1%7D%5Eq%20(y_%7Bd%2Ck%7D-y_k)%5E2%7D%20%5Cover%20%5Cpartial%20y_o%7D%0A%20%3D%20%7B1%20%5Cover%202%7D%20%5Csum_%7Bk%3D1%7D%5Eq%20%7B%5Cpartial%20(y_%7Bd%2Ck%7D-y_k)%5E2%20%5Cover%20%5Cpartial%20y_o%7D%0A%20%3D%20%7B1%20%5Cover%202%7D%20%5Csum_%7Bk%3D1%7D%5Eq%20%7B%7B%5Cpartial%20(y_%7Bd%2Ck%7D-y_k)%5E2%20%5Cover%20%5Cpartial%20y_k%7D%5Ccdot%7B%5Cpartial%20y_k%20%5Cover%20%5Cpartial%20y_o%7D%7D%5C%5C%0A%20%26%3D%20-%20%5Csum_%7Bk%3D1%7D%5Eq%20(y_%7Bd%2Ck%7D-y_k)%20%5Ccdot%20%7B%5Cpartial%20y_k%20%5Cover%20%5Cpartial%20y_o%7D%0A%20%3D%20-%20%5Csum_%7Bk%3D1%7D%5Eq%20e_k%20%5Ccdot%20%7B%5Cpartial%20y_k%20%5Cover%20%5Cpartial%20y_o%7D%0A%5Cend%7Balign*%7D)

**Comment by walkerlala** [comment]
Thanks you very much!!
