### ISSUE TITLE
Local Preview

### ISSUE THREAD

**Issue by longlongvip** [parpalak/upmath.me#32]
I install the upmath.me, but the preview doesn't work
[![OEMkn0.png](https://s1.ax1x.com/2022/05/04/OEMkn0.png)](https://imgtu.com/i/OEMkn0)

**Comment by parpalak** [comment]
Hi. Thanks for the message. I am doing this project in my spare time, and there is very little of it. Unfortunately, I cannot provide support for separate installations of Upmath.
