### ISSUE TITLE
Can the artifacts be downloaded instead of being hosted to the server?

### ISSUE THREAD

**Issue by iago-lito** [parpalak/upmath.me#34]
Hello, and thank you for upmath :)

I am curious whether the parts rendered by [i.upmath.me](https://i.upmath.me) can be directly embedded into the resulting html code as `<svg>` tags or base64, instead of remaining hosted on the server?

**Comment by parpalak** [comment]
Hello,

Certainly, embedding parts from i.upmath.me directly into the resulting HTML code as <svg> tags is technically feasible. You can see it in action on the Upmath website itself:

![image](https://github.com/parpalak/upmath.me/assets/9402484/5a9bcd07-851a-429e-9f7e-8ebe7f568684)

**Comment by iago-lito** [comment]
Okay, thank you. So if I want to download this as the rendering result, I need to open the console and copy-paste it from there?

**Comment by parpalak** [comment]
This is a possible option, but not convenient. I'll think about how to simplify it.

**Comment by iago-lito** [comment]
Hello, and thank you for having addressed this :) I don't see a difference yet on the two-sided editor, and the `html` button still yields a document in which `svg` nodes are hosted at [i.upmath.me](https://i.upmath.me). Maybe an alternate `html-standalone` button would be the easiest way to replace them by actual svg directives?

(still, I can always get this from the console as you showed)

**Comment by parpalak** [comment]
Apologies for any confusion – I forgot to mention that it operates in a not-so-obvious manner :)
If you click on the download button within the "preview" tab, you'll receive an HTML markup with embedded SVG. The functionality of the other tabs remains unchanged. Previously, pressing the download button in the "preview" tab resulted in downloading the same markup as in the "html" tab. Thank you for your understanding!

**Comment by iago-lito** [comment]
Oh, great! So I just works out of the box now and we don't even need to think about it! Perfect. Thank you so much <3
