### ISSUE TITLE
Issues on mindmap rendering

### ISSUE THREAD

**Issue by HaydarJawad** [parpalak/upmath.me#37]
Hi, thank you very much for a great package. I have tried some other diagrams from the TikZ library, but they don't render. Am I doing something wrong?

For example, this doesn't render:

$$
\usetikzlibrary {mindmap}
\tikz[mindmap,concept color=red!50]
  \node [concept] {Root concept}
    child[grow=right] {node[concept] {Child concept}};$$
    
    thank you

**Comment by parpalak** [comment]
`\tikz` is not supported by the service right now. You can use `\begin{tikzpicture}` instead:

```
$$
\usetikzlibrary {mindmap}
\begin{tikzpicture}[mindmap,concept color=red!50]
  \node [concept] {Root concept}
    child[grow=right] {node[concept] {Child concept}};
\end{tikzpicture}
$$
```

The result:
![](https://i.upmath.me/svg/%5Cusetikzlibrary%20%7Bmindmap%7D%0A%5Cbegin%7Btikzpicture%7D%5Bmindmap%2Cconcept%20color%3Dred!50%5D%0A%20%20%5Cnode%20%5Bconcept%5D%20%7BRoot%20concept%7D%0A%20%20%20%20child%5Bgrow%3Dright%5D%20%7Bnode%5Bconcept%5D%20%7BChild%20concept%7D%7D%3B%0A%5Cend%7Btikzpicture%7D)

**Comment by HaydarJawad** [comment]
Thank you, mate! Still, some exactly the same as yours do not show the edge from the centre circle. Not sure if it's me (see below from the Upmath editor). What I have noticed is that some complex ones do not render, not sure why, even with \begin{tikzpicture}.
 

\usetikzlibrary {mindmap}
\begin{tikzpicture}
  \path[mindmap,concept color=black,text=white]
    node[concept] {Computer Science}
    [clockwise from=0]
    % note that `sibling angle' can only be defined in
    % `level 1 concept/.append style={}'
    child[concept color=green!50!black] {
      node[concept] {practical}
      [clockwise from=90]
      child { node[concept] {algorithms} }
      child { node[concept] {data structures} }
      child { node[concept] {pro\-gramming languages} }
      child { node[concept] {software engineer\-ing} }
    }
    % note that the `concept color' is passed to the `child'(!)
    child[concept color=blue] {
      node[concept] {applied}
      [clockwise from=-30]
      child { node[concept] {databases} }
      child { node[concept] {WWW} }
    }
    child[concept color=red] { node[concept] {technical} }
    child[concept color=orange] { node[concept] {theoretical} };
\end{tikzpicture}


![Screenshot 2024-07-15 at 14 28 26](https://github.com/user-attachments/assets/7f4f0277-f188-4cfd-bb3d-29b17d3dc261)

**Comment by parpalak** [comment]
I see what the problem is. I need some time to figure it out.

**Comment by HaydarJawad** [comment]
OK, mate thank you. again the package  is amazing!

**Comment by parpalak** [comment]
The problem with gradients can be fixed, but other problems pop up that seem more serious to me. So far I've opened a related issue in the PGF project, let's take a look at their response: https://github.com/pgf-tikz/pgf/issues/1353

**Comment by HaydarJawad** [comment]
Thank you mate!

**Comment by parpalak** [comment]
As you can see, there is no clear reaction in the associated pull request. It is unclear whether the reported issue is recognized as a bug or if it needs to be addressed elsewhere. And if it is acknowledged, whether someone will fix it and when. It seemed to me that the dvisvgm driver for pgf is somewhat raw, and it is unclear how prioritized its support is. Moreover, the last release of pgf was a year and a half ago.

Given all this, I created a special workaround command that enables the dvisvgm driver only if it is specified. If there are problems with a smooth color transition, you need to add `\dvisvgm` at the beginning and check that there are no other issues with rendering images:

```
\dvisvgm
\usetikzlibrary {mindmap}
  \tikz[mindmap,concept color=blue!80]
    \node [concept] {Root concept}
      child[concept color=red,grow=30] {node[concept] {Child concept}}
      child[concept color=orange,grow=0]  {node[concept] {Child concept}};
```

![](https://i.upmath.me/svg/%5Cdvisvgm%0A%5Cusetikzlibrary%20%7Bmindmap%7D%0A%20%20%5Ctikz%5Bmindmap%2Cconcept%20color%3Dblue!80%5D%0A%20%20%20%20%5Cnode%20%5Bconcept%5D%20%7BRoot%20concept%7D%0A%20%20%20%20%20%20child%5Bconcept%20color%3Dred%2Cgrow%3D30%5D%20%7Bnode%5Bconcept%5D%20%7BChild%20concept%7D%7D%0A%20%20%20%20%20%20child%5Bconcept%20color%3Dorange%2Cgrow%3D0%5D%20%20%7Bnode%5Bconcept%5D%20%7BChild%20concept%7D%7D%3B)

**Comment by HaydarJawad** [comment]
*Thank you, mate! There is also a strange behaviour I discovered which I
tried because I encountered it   before with another rendering app! The
issue was: With white spaces removed, it works in some! For example, this
will not render*

$$
\usetikzlibrary {arrows.meta,automata,positioning,shadows}
\begin{tikzpicture}
  [shorten >=1pt,node distance=2cm,on grid,>={Stealth[round]},thick,
   every state/.style={fill,draw=none,orange,text=white,circular drop
shadow},
   accepting/.style ={green!50!black,text=white},
   initial/.style ={red,text=white}]

  \node[state,initial]  (q_0)                      {$q_0$};
  \node[state]          (q_1) [above right=of q_0] {$q_1$};
  \node[state]          (q_2) [below right=of q_0] {$q_2$};
  \node[state,accepting](q_3) [below right=of q_1] {$q_3$};

  \path[->] (q_0) edge              node [above left]  {0} (q_1)
                  edge              node [below left]  {1} (q_2)
            (q_1) edge              node [above right] {1} (q_3)
                  edge [loop above] node               {0} ()
            (q_2) edge              node [below right] {0} (q_3)
                  edge [loop below] node               {1} ();
\end{tikzpicture}
$$


*However, if I use an online whitespace remover like:
https://codebeautify.org/remove-extra-spaces#
<https://codebeautify.org/remove-extra-spaces#>, the result will be*

$$
\usetikzlibrary {arrows.meta,automata,positioning,shadows}
\begin{tikzpicture} [shorten >=1pt,node distance=2cm,on
grid,>={Stealth[round]},thick, every
state/.style={fill,draw=none,orange,text=white,circular drop shadow},
accepting/.style ={green!50!black,text=white}, initial/.style
={red,text=white}] \node[state,initial] (q_0) {$q_0$}; \node[state] (q_1)
[above right=of q_0] {$q_1$}; \node[state] (q_2) [below right=of q_0]
{$q_2$}; \node[state,accepting](q_3) [below right=of q_1] {$q_3$};
\path[->] (q_0) edge node [above left] {0} (q_1) edge node [below left] {1}
(q_2) (q_1) edge node [above right] {1} (q_3) edge [loop above] node {0} ()
(q_2) edge node [below right] {0} (q_3) edge [loop below] node {1} ();
\end{tikzpicture}
$$

*And this will render with no issues. Best wishes and thank you again*
