### ISSUE TITLE
Support additional way to create equations besides $

### ISSUE THREAD

**Issue by OhadRubin** [parpalak/upmath.me#39]
Hey,
I use your site to render outputs from ChatGPT and he sometimes uses \( math here \) \[ \] for multiline equations (as I wrote this sentence I understood why this isn't supported).
```
he sometimes uses \( math here \) \[ math here \]
```
Is it possible to add a special mode to accommodate for that feature?

**Comment by parpalak** [comment]
It's not that simple; we've already discussed this here: https://github.com/parpalak/upmath.me/issues/12.

I would recommend asking ChatGPT to consistently use double dollar signs:

![image](https://github.com/user-attachments/assets/ce074149-e946-4f8a-afe1-5e79493dad4d)

![image](https://github.com/user-attachments/assets/eab997d3-1b1b-4915-8666-0ecd185e2ee9)
