### ISSUE TITLE
Add support for \usepackage{ stmaryrd }

### ISSUE THREAD

**Issue by basvdheuvel** [parpalak/upmath.me#6]
I'd like to use double brackets (`\llbracket \rrbracket`), which are in stmaryrd, currently not supported. Please add support. Thanks!

**Comment by parpalak** [comment]
I've added the package. You can [use it now](http://tex.s2cms.com/g/%5Cvarotimes%20%5CLongmapsfrom%20%20%5Cleft%5Cllbracket%20%20%0Ae%20%3D%202%20%2B%20%5Ccfrac%7B1%7D%7B%0A%20%201%20%2B%20%5Ccfrac%7B1%7D%7B%0A%20%20%20%202%20%2B%20%5Ccfrac%7B2%7D%7B%0A%20%20%20%20%20%203%20%2B%20%5Ccfrac%7B3%7D%7B%0A%20%20%20%20%20%20%20%204%20%2B%20%5Ccfrac%7B4%7D%7B%5Cldots%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%5Cright%5Crrbracket).
