### ISSUE TITLE
Is there a way to set to default when accessing the webpage?

### ISSUE THREAD

**Issue by BrightFeather** [parpalak/upmath.me#8]

**Comment by parpalak** [comment]
What do you mean by "set to default"? What do you want to set?

**Comment by BrightFeather** [comment]
I meant to set to the webpage with your original code. I found out that I need to clear the cookies for that site.

**Comment by parpalak** [comment]
Actually it's the localstorage, not cookies. As I wrote in that code,

> If you want to see the instruction again, open the editor in a private tab, in a different browser or download and clear your post and refresh the page.

So you can erase your text and refresh the page.
