### ISSUE TITLE
Is there a way to display latex tables?

### ISSUE THREAD

**Issue by BrightFeather** [parpalak/upmath.me#9]
A typical table goes like:
```
\begin{table}
\begin{tabular}
...
\end{tabular}
\end{table}
```

**Comment by parpalak** [comment]
You need only `tabular` environment:

```
\begin{tabular}{ l | c | r }
    \hline
    1 & 2 & 3 \\ \hline
    4 & 5 & 6 \\ \hline
    7 & 8 & 9 \\
    \hline
\end{tabular}
```
It's rendered this way:
![](https://tex.s2cms.ru/svg/%5Cbegin%7Btabular%7D%7B%20l%20%7C%20c%20%7C%20r%20%7D%0A%20%20%20%20%5Chline%0A%20%20%20%201%20%26%202%20%26%203%20%5C%5C%20%5Chline%0A%20%20%20%204%20%26%205%20%26%206%20%5C%5C%20%5Chline%0A%20%20%20%207%20%26%208%20%26%209%20%5C%5C%0A%20%20%20%20%5Chline%0A%20%20%5Cend%7Btabular%7D)

**Comment by BrightFeather** [comment]
I see. thanks!

**Comment by chaserene** [comment]
@parpalak this doesn't work for me. I inserted your [above snippet](https://github.com/parpalak/upmath.me#issuecomment-361367313) into https://upmath.me/ and it doesn't render as a table, it remains text. did something break this feature?

**Comment by parpalak** [comment]
Upmath = Markdown + LaTeX. You need `$$` to switch from Markdown to LaTeX mode.
![image](https://user-images.githubusercontent.com/9402484/108848279-7a9ef680-75e9-11eb-97ed-fdb798ec3159.png)

**Comment by chaserene** [comment]
@parpalak a-ha. thank you!
